import * as pps from "../../assets/pps";
import Theme from "./theme";
export default [
  {
    key: "0",
    des1: "Leon Garcia",
    img: pps.x1,
    badgeId: 0,
    DetailedColor: Theme.Gradients.g1,
    num: "(555) 232 1224",
  },
  {
    key: "1",
    des1: "Cameron George",
    img: pps.x3,
    badgeId: 1,
    DetailedColor: Theme.Gradients.g2,
    num: "(555) 232 1224",
  },
  {
    key: "2",
    des1: "Eddie Reid",
    img: pps.x2,
    badgeId: 2,
    DetailedColor: Theme.Gradients.g3,
    num: "(555) 232 1224",
  },
  {
    key: "3",
    des1: "Johanna Gill",
    img: pps.x4,
    badgeId: 3,
    DetailedColor: Theme.Gradients.g4,
    num: "(555) 232 1224",
  },
  {
    key: "4",
    des1: "Micheal",
    img: pps.x5,
    badgeId: 4,
    DetailedColor: Theme.Gradients.g5,
    num: "(555) 232 1224",
  },
  {
    key: "5",
    des1: "Brian Owens",
    img: pps.x6,
    badgeId: 5,
    DetailedColor: Theme.Gradients.g6,
    num: "(555) 232 1224",
  },
  {
    key: "6",
    des1: "Marbin Harrison",
    img: pps.x7,
    badgeId: 0,
    DetailedColor: Theme.Gradients.g7,
    num: "(555) 232 1224",
  },
  {
    key: "7",
    des1: "Lewis Sutton",
    img: pps.x8,
    badgeId: 1,
    DetailedColor: Theme.Gradients.g8,
    num: "(555) 232 1224",
  },
];
